<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body style="background-color: #eee;">
    <div id="container" style="max-width: 600px; min-width: 200px; background-color: #FFF; padding: 20px; margin: auto;">
        <img src="https://i.imgur.com/WwpjYi3.jpg" alt="Logo" style="width: 700px; height: 275px;">
